-- ============================================================
-- FarmTech Solutions — Fase 3
-- Consultas SQL — Oracle
-- Tabela: FARMTECH_SENSORES
-- Autor: Kauan Maciel Forgiarini — RM574005
-- FIAP — Inteligência Artificial — 2026
-- ============================================================

-- 1. VISUALIZAR TODOS OS DADOS
SELECT * FROM FARMTECH_SENSORES;


-- 2. REGISTROS EM QUE A BOMBA FOI ACIONADA
SELECT DATA_HORA, UMIDADE_PCT, PH_SOLO, CHUVA_MM
FROM FARMTECH_SENSORES
WHERE BOMBA_LIGADA = 1
ORDER BY DATA_HORA;


-- 3. MÉDIAS GERAIS DOS PARÂMETROS DO SOLO
SELECT
    ROUND(AVG(UMIDADE_PCT), 2)    AS MEDIA_UMIDADE,
    ROUND(AVG(TEMPERATURA_C), 2)  AS MEDIA_TEMPERATURA,
    ROUND(AVG(PH_SOLO), 2)        AS MEDIA_PH,
    ROUND(AVG(CHUVA_MM), 2)       AS MEDIA_CHUVA
FROM FARMTECH_SENSORES;


-- 4. CONTAGEM DE ACIONAMENTOS DA BOMBA POR DIA
SELECT
    SUBSTR(DATA_HORA, 1, 10) AS DIA,
    COUNT(*) AS TOTAL_IRRIGACOES
FROM FARMTECH_SENSORES
WHERE BOMBA_LIGADA = 1
GROUP BY SUBSTR(DATA_HORA, 1, 10)
ORDER BY DIA;


-- 5. LEITURAS COM pH FORA DA FAIXA IDEAL PARA SOJA (5.5 a 7.0)
SELECT DATA_HORA, PH_SOLO, UMIDADE_PCT
FROM FARMTECH_SENSORES
WHERE PH_SOLO < 5.5 OR PH_SOLO > 7.0
ORDER BY DATA_HORA;


-- 6. DIAS COM MAIOR UMIDADE MÉDIA
SELECT
    SUBSTR(DATA_HORA, 1, 10) AS DIA,
    ROUND(AVG(UMIDADE_PCT), 2) AS MEDIA_UMIDADE
FROM FARMTECH_SENSORES
GROUP BY SUBSTR(DATA_HORA, 1, 10)
ORDER BY MEDIA_UMIDADE DESC;


-- 7. TOTAL DE REGISTROS E PERCENTUAL DE IRRIGACAO
SELECT
    COUNT(*) AS TOTAL_REGISTROS,
    SUM(BOMBA_LIGADA) AS TOTAL_IRRIGACOES,
    ROUND(SUM(BOMBA_LIGADA) * 100.0 / COUNT(*), 1) AS PERC_IRRIGACAO
FROM FARMTECH_SENSORES;


-- 8. REGISTROS COM CHUVA PREVISTA > 5mm (bomba deve estar desligada)
SELECT DATA_HORA, CHUVA_MM, BOMBA_LIGADA
FROM FARMTECH_SENSORES
WHERE CHUVA_MM > 5
ORDER BY CHUVA_MM DESC;


-- 9. VALORES MINIMOS E MAXIMOS DE CADA SENSOR
SELECT
    MIN(UMIDADE_PCT)    AS MIN_UMIDADE,
    MAX(UMIDADE_PCT)    AS MAX_UMIDADE,
    MIN(TEMPERATURA_C)  AS MIN_TEMP,
    MAX(TEMPERATURA_C)  AS MAX_TEMP,
    MIN(PH_SOLO)        AS MIN_PH,
    MAX(PH_SOLO)        AS MAX_PH
FROM FARMTECH_SENSORES;
