-- ============================================================
-- FarmTech Solutions — Fase 3
-- Consultas SQL — Oracle | Tabela: SENSOR_FARMTECH
-- Kauan Maciel Forgiarini — RM574005 | FIAP IA 2026
-- ============================================================

-- 1. VISUALIZAR TODOS OS DADOS (obrigatória)
SELECT * FROM SENSOR_FARMTECH ORDER BY ID;

-- 2. REGISTROS COM BOMBA ACIONADA
SELECT * FROM SENSOR_FARMTECH
WHERE BOMBA_LIGADA = 1
ORDER BY ID;

-- 3. MÉDIAS DOS PARÂMETROS DO SOLO
SELECT
    ROUND(AVG(PH_SOLO), 2)          AS MEDIA_PH,
    ROUND(AVG(UMIDADE_SOLO_PCT), 1) AS MEDIA_UMIDADE,
    ROUND(AVG(TEMPERATURA_C), 1)    AS MEDIA_TEMP
FROM SENSOR_FARMTECH;

-- 4. DISTRIBUIÇÃO DOS MOTIVOS DE DECISÃO
SELECT MOTIVO_DECISAO, COUNT(*) AS OCORRENCIAS
FROM SENSOR_FARMTECH
GROUP BY MOTIVO_DECISAO
ORDER BY OCORRENCIAS DESC;

-- 5. TOTAIS E PERCENTUAL DE IRRIGAÇÃO
SELECT
    COUNT(*)                          AS TOTAL_LEITURAS,
    SUM(BOMBA_LIGADA)                 AS VEZES_IRRIGOU,
    ROUND(AVG(BOMBA_LIGADA)*100, 1)   AS PCT_IRRIGANDO
FROM SENSOR_FARMTECH;

-- 6. pH FORA DA FAIXA IDEAL PARA SOJA (5.5 a 7.0)
SELECT ID, TIMESTAMP_LEITURA, PH_SOLO, UMIDADE_SOLO_PCT, BOMBA_LIGADA
FROM SENSOR_FARMTECH
WHERE PH_SOLO < 5.5 OR PH_SOLO > 7.0
ORDER BY PH_SOLO;

-- 7. LEITURAS COM CHUVA PREVISTA > 5mm
SELECT ID, TIMESTAMP_LEITURA, CHUVA_PREVISTA_MM, BOMBA_LIGADA, MOTIVO_DECISAO
FROM SENSOR_FARMTECH
WHERE CHUVA_PREVISTA_MM > 5
ORDER BY CHUVA_PREVISTA_MM DESC;

-- 8. MÍNIMOS E MÁXIMOS DE CADA SENSOR
SELECT
    MIN(UMIDADE_SOLO_PCT)   AS MIN_UMIDADE,   MAX(UMIDADE_SOLO_PCT)   AS MAX_UMIDADE,
    MIN(TEMPERATURA_C)      AS MIN_TEMP,       MAX(TEMPERATURA_C)      AS MAX_TEMP,
    MIN(PH_SOLO)            AS MIN_PH,         MAX(PH_SOLO)            AS MAX_PH
FROM SENSOR_FARMTECH;

-- 9. UMIDADE MÉDIA POR DIA
SELECT
    SUBSTR(TIMESTAMP_LEITURA, 1, 10)    AS DIA,
    ROUND(AVG(UMIDADE_SOLO_PCT), 1)     AS MEDIA_UMIDADE
FROM SENSOR_FARMTECH
GROUP BY SUBSTR(TIMESTAMP_LEITURA, 1, 10)
ORDER BY DIA;

-- 10. CONTAGEM DE IRRIGAÇÕES POR DIA
SELECT
    SUBSTR(TIMESTAMP_LEITURA, 1, 10)    AS DIA,
    COUNT(*)                            AS TOTAL_IRRIGACOES
FROM SENSOR_FARMTECH
WHERE BOMBA_LIGADA = 1
GROUP BY SUBSTR(TIMESTAMP_LEITURA, 1, 10)
ORDER BY DIA;
